import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  list: {
    marginTop: 0,
  },
  loadingContainer: {
    paddingVertical: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyContainer: {
    width: 353,
    height: 158,
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingTop: 60,
    paddingRight: 12,
    paddingBottom: 60,
    paddingLeft: 12,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    alignSelf: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  emptyText: {
    fontFamily: 'Commissioner',
    fontWeight: '700',
    fontSize: 14,
    lineHeight: 14,
    color: '#7A7E85',
    textAlign: 'center',
  },
  emptySubtext: {
    fontFamily: 'Commissioner',
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 14,
    color: '#D3D6D7',
    textAlign: 'center',
  },
});
