import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 24,
    marginBottom: 24,
    gap: 12,
  },
  card: {
    flex: 1,
    backgroundColor: 'white',
    borderRadius: 16,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  iconContainer: {
    width: 28,
    height: 28,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 4,
  },
  changeIndicator: {
    width: 47,
    height: 23,
    borderRadius: 12,
    backgroundColor: '#FAFAFA',
    padding: 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  changeText: {
    fontSize: 10,
    fontWeight: '500',
    fontFamily: 'Commissioner-Medium',
    lineHeight: 10,
  },
  changeIcon: {
    width: 10,
    height: 6,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: -3,
  },
  cardLabel: {
    fontSize: 12,
    fontWeight: '400',
    fontFamily: 'Commissioner-Regular',
    color: '#333',
    lineHeight: 12,
    marginBottom: 8,
  },
  cardAmount: {
    fontSize: 20,
    fontWeight: '700',
    fontFamily: 'Commissioner-Bold',
    color: '#000',
    lineHeight: 20,
  },
});